version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
    depends_on:
      - redis
      - mysql
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - app-network

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: findCompanionsDB
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

volumes:
  redis-data:
  mysql-data:

networks:
  app-network:
    driver: bridge